# Dependabot Configuration File
# This file enables Dependabot to automatically check for dependencies updates.
# For more details on configuration options, visit:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies (if using pip)
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly" 
    open-pull-requests-limit: 10 
    ignore:
      - dependency-name: "some-package" 
        versions: ["1.x", "2.x"]  
    assignees:
      - "maiz-an"  
      - "sumalka"
    reviewers:
      - "maiz-an" 
      - "sumalka"

  # GitHub Actions updates (if using GitHub Actions)
  - package-ecosystem: "github-actions"
    directory: "/"  
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "maiz-an"
      - "sumalka"
    reviewers:
      - "maiz-an"
      - "sumalka"
