name: "Spidynal Action"
description: "Run SPIDYNAL, a Spider-Man-themed utility for network speed testing and file searching, in your GitHub workflow."
author: "maiz-an"

inputs:
  command:
    description: "Command to pass to SPIDYNAL.exe (e.g., 'net speed', 'spidy lens')"
    required: true
    default: "net speed"
  query:
    description: "Query for spidy lens (e.g., file name)"
    required: false
  extension:
    description: "File extension for spidy lens (e.g., '.txt')"
    required: false

runs:
  using: "composite"
  steps:
    - name: Run SPIDYNAL.exe
      shell: cmd
      run: |
        SPIDYNAL.exe ${{ inputs.command }} ${{ inputs.query }} ${{ inputs.extension }}

branding:
  icon: "code"
  color: "red"
