name: "Spidynal Action"
description: "Run SPIDYNAL, a Spider-Man-themed utility for network speed testing and file searching, in your GitHub workflow."
author: "YourGitHubUsername"

inputs:
  command:
    description: "Command to pass to SPIDYNAL.exe (e.g., 'net speed', 'spidy lens')"
    required: true
    default: "net speed"

runs:
  using: "composite"
  steps:
    - name: Run SPIDYNAL.exe
      shell: cmd
      run: |
        SPIDYNAL.exe ${{ inputs.command }}

branding:
  icon: "spider-web"
  color: "red"
