name: Test SPIDYNAL Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test-spidynal:
    runs-on: windows-latest # Docker with Windows image needs a Windows runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run SPIDYNAL Action - Net Speed
        uses: ./
        with:
          command: "net speed"

      - name: Run SPIDYNAL Action - Spidy Lens
        uses: ./
        with:
          command: "spidy lens"
